export const illDefinedConditions: string[] = [
  'cardiac death',
  'cardiac arrest',
  'cardiac failure',
  'heart failure',
  'ventricular failure',
  'hypotension',
  'respiratory failure',
  'tachycardia',
  'bradycardia',
  'palpitations',
  'pulseless',
  'abnormal heart beat',
  'benign and innocent cardiac murmurs',
  'cardiac sounds',
  'gangrene',
  'elevated blood-pressure',
  'low blood-pressure',
  'epistaxis',
  'haemorrhage from throat',
  'haemoptysis',
  'haemorrhage in respiratory passages',
  'cough',
  'dyspnoea',
  'stridor',
  'wheezing',
  'periodic breathing',
  'hyperventilation',
  'mouth breathing',
  'hiccough',
  'sneezing',
  'abnormalities of breathing',
  'throat pain',
  'chest pain',
  'precordial pain',
  'asphyxia',
  'pleurisy',
  'respiratory arrest',
  'abnormal sputum',
  'acute abdomen',
  'upper abdomen pain',
  'pelvic pain',
  'lower abdomen pain',
  'abdominal pain',
  'nausea and vomiting',
  'heartburn',
  'dysphagia',
  'flatulence',
  'incontinence',
  'hepatomegaly',
  'splenomegaly',
  'hyperbilurubinaemia',
  'jaundice',
  'ascites',
  'swelling, mass, lump ',
  'abnormal bowel sounds',
  'peristalsis',
  'abdominal rigidity',
  'change in bowel habit',
  'faecal abnormalities',
  'halitosis',
  'disturbances of skin sensation',
  'anaesthesia of skin',
  'hypoaesthesia of skin',
  'paraesthesia of skin',
  'hyperaesthesia',
  'rash, skin eruption',
  'skin eruption',
  'swelling, mass and lump',
  'cyanosis',
  'pallor',
  'flushing',
  'spontaneous ecchymoses',
  'changes in skin texture',
  'abnormal head movements',
  'tremor',
  'cramp and spasm',
  'fasciculation',
  'abnormal involuntary movements',
  'ataxic gait',
  'paralytic gait',
  'difficulty in walking',
  'immobility',
  'abnormalities of gait and mobility',
  'lack of coordination',
  'ataxia',
  'tetany',
  'meningismus',
  'abnormal reflex',
  'abnormal posture',
  'clicking hip',
  'tendency to fall',
  'pain associated with micturition',
  'dysuria',
  'vesical tenesmus',
  'painful micturition',
  'haematuria',
  'urinary incontinence',
  'retention of urine',
  'anuria and oliguria',
  'polyuria',
  'urethral discharge',
  'symptoms and signs involving urinary system',
  'extravasation of urine',
  'difficulties with micturition',
  'extrarenal uraemia',
  'somnolence',
  'stupor',
  'coma',
  'disorientation',
  'anterograde amnesia',
  'retrograde amnesia',
  'other amnesia',
  'dizziness and giddiness',
  'disturbances of smell and taste',
  'anosmia',
  'parosmia',
  'parageusia',
  'auditory hallucinations',
  'visual hallucinations',
  'other hallucinations',
  'hallucinations',
  'nervousness',
  'restlessness and agitation',
  'unhappiness',
  'demoralization and apathy',
  'irritability and anger',
  'hostility',
  'physical violence',
  'emotional shock and stress',
  'low level of personal hygiene',
  'bizarre personal appearance',
  'strange and inexplicable behaviour',
  'overactivity',
  'slowness and poor responsiveness',
  'suspiciousness and evasiveness',
  'verbosity and circumstantial detail obscuring reason for contact',
  'dysphasia and aphasia',
  'dysarthria and anarthria',
  'other and unspecified speech disturbances',
  'dyslexia and other symbolic dysfunctions',
  'dyslexia and alexia',
  'agnosia',
  'apraxia',
  'voice disturbances',
  'dysphonia',
  'aphonia',
  'hypernasality and hyponasality',
  'other and unspecified voice disturbances',
  'fever',
  'drug-induced fever',
  'other specified fever',
  'headache',
  'pain',
  'malaise and fatigue',
  'senility',
  'syncope and collapse',
  'convulsions',
  'shock',
  'enlarged lymph nodes',
  'systemic inflammatory response syndrome',
  'hypothermia',
  'dry mouth',
  'clubbing of fingers',
  'elevated erythrocyte sedimentation rate',
  'abnormal plasma viscosity',
  'abnormality of red blood cells',
  'abnormality of white blood cells',
  'elevated blood glucose level',
  'abnormal glucose tolerance test',
  'hyperglycaemia',
  'abnormal serum enzyme levels',
  'elevation of levels of transaminase and lactic acid dehydrogenase [ldh]',
  'abnormal levels of other serum enzymes',
  // 'laboratory evidence of human immunodeficiency virus [hiv]',
  'raised antibody titre',
  'abnormal reaction to tuberculin test',
  'false-positive serological test for syphilis',
  'abnormality of albumin',
  'abnormality of globulin',
  'abnormality of alphafetoprotein',
  'abnormalities of plasma proteins',
  'alcohol in blood',
  'opiate drug in blood',
  'cocaine in blood',
  'hallucinogen in blood',
  'drugs of addictive potential in blood',
  'psychotropic drug in blood',
  'steroid agent in blood',
  'abnormal level of heavy metals in blood',
  'abnormal level of blood mineral',
  'isolated proteinuria',
  'glycosuria',
  'chyluria',
  'myoglobinuria',
  'biliuria',
  'haemoglobinuria',
  'acetonuria',
  'abnormal urine levels',
  'abnormal findings in urine',
  'abnormal findings in cerebrospinal fluid',
  'abnormal findings in specimens from respiratory organs and thorax',
  'abnormal findings in specimens from digestive organs and abdominal cavity',
  'abnormal findings in specimens from male genital organs',
  'abnormal findings in specimens from female genital organs',
  'abnormal findings in specimens from other organs, systems and tissues',
  'space-occupying lesion',
  'abnormal findings in lung',
  'abnormal findings in breast',
  'abnormal findings in skull and head',
  'abnormal findings in heart and coronary circulation',
  'abnormal findings in liver and biliary tract',
  'abnormal findings in digestive tract',
  'abnormal findings on diagnostic imaging of urinary organs',
  'abnormal findings on diagnostic imaging of other abdominal regions',
  'abnormal findings on diagnostic imaging of limbs',
  'abnormal findings on diagnostic imaging of other parts of musculoskeletal system',
  'abnormal findings on diagnostic imaging of other specified body structures',
  'Abnormal results of function studies',
  'sudden adult death syndrome',
  'sudden unexplained nocturnal death',
  'death occurring less than 24 hours',
  'unattended death',
  'found dead',
  'unspecified cause of mortality',
  'unknown',
  // 'undetermined',
  'natural death',
  'cause indeterminant',
  'cause never determined',
  'cause not determined',
  'cause not found',
  'cause not known',
  'cause uncertain',
  // 'cause undetermined',
  'cause unknown',
  'causes indeterminant',
  'causes never determined',
  'causes not determined',
  'causes not found',
  'causes not known',
  'unknown cause of mortality',
  'etiology unknown',
  // 'natural cause undetermined',
  'not known',
  // 'origin undetermined',
  'uncertain cause',
  'uncertain etiology',
  // 'undetermined cause',
  // 'undetermined etiology',
  'natural cause',
  'natural disease',
  'unknown origin',
  'unknown cause',
  'unknown specific cause'
]
